#!/bin/bash

RevDate="Unknown date"
RevNum=-1

if [ -d ".svn" ]; then
    RevDate=`svn info | grep "Last Changed Date" | awk -F'[()]' '{ print $2 }'`
    RevNum=`svn info | grep "Last Changed Rev" | awk -F'[ :]+' '{ print $4 }'`
fi

echo "Building RTZen revision ${RevNum}, Snapshot from ${RevDate}";

echo "
/******************************************************************************\\
  | This file is auto generated by the build script. Do not modify manually.     |
  |                                                                              |
  | @author Krishna Raman                                                        |
  | @since 6 Jun 2004                                                            |
  |                                                                              |
  \\******************************************************************************/
package edu.uci.ece.zen.utils;

public class VersionStamp{
    public static final String versionDate=\"${RevDate}\";
    public static final int versionRev=${RevNum};
}" > packages/src/edu/uci/ece/zen/utils/VersionStamp.java
