/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class perf_cPrint_nativePrinter */

#ifndef _Included_perf_cPrint_nativePrinter
#define _Included_perf_cPrint_nativePrinter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     perf_cPrint_nativePrinter
 * Method:    print
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_perf_cPrint_nativePrinter_print
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
