/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uci_ece_zen_orb_transport_serial_NativeSerialPort */

#ifndef _Included_edu_uci_ece_zen_orb_transport_serial_NativeSerialPort
#define _Included_edu_uci_ece_zen_orb_transport_serial_NativeSerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uci_ece_zen_orb_transport_serial_NativeSerialPort
 * Method:    getMessage
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_edu_uci_ece_zen_orb_transport_serial_NativeSerialPort_getMessage
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_uci_ece_zen_orb_transport_serial_NativeSerialPort
 * Method:    setMessage
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_edu_uci_ece_zen_orb_transport_serial_NativeSerialPort_setMessage
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
