package edu.uci.ece.zen.poa.mechanism;

public final class SystemIdStrategy extends IdAssignmentStrategy {
    private int id;

    /**
     * Create System Id Strategy Strat key genration from 0
     */
    public SystemIdStrategy() {
        this.id = 0;
    }

   /**
    * Obtain new system id.
    * @return byte[]
    */
    public void nextId( FString id_out ){
        ++id;

        id_out.append((byte) ((value >>> 24) & 0xFF) );
        id_out.append((byte) ((value >>> 16) & 0xFF) );
        id_out.append((byte) ((value >>> 8) & 0xFF) );
        id_out.append((byte) (value & 0xFF) );
    }
    
   /**
    * Check if strategy same as this strategy
    * @param policyName policy type
    * @return boolean
    */
    public boolean isPresent(int policyName) {
        return IdAssignmentStrategy.SYSTEM_ID == policyName;
    }
    
   /**
    * validate policy type
    * @param policy policy-type
    */
    public boolean validate(int policy){
        return isPresent(policy);
    }

    /**
     * Verify if the id was generated by this strategy
     * @param id
     * @return boolean true if yes, else false
     */
   public boolean verifyID( FString id_in ) {
       return true;
   }
}
