/* --------------------------------------------------------------------------*
 * $Id: UserIdStrategy.java,v 1.1 2003/11/26 22:29:04 nshankar Exp $
 *--------------------------------------------------------------------------*/

package edu.uci.ece.zen.poa.mechanism;


public final class UserIdStrategy extends IdAssignmentStrategy {
    
    /**
     * Create user id strategy
     */
    public UserIdStrategy() {}

   /**
    * Obtain next Id -- defaults to exception being thrown.
    * @return byte[] next id
    * @throws org.omg.PortableServer.POAPackage.WrongPolicy
    */
    public byte[] nextId() throws
                org.omg.PortableServer.POAPackage.WrongPolicy {
        throw new org.omg.PortableServer.POAPackage.WrongPolicy();
    }

   /**
    * Checks if policy type corresonds to this strategy
    * @param policyName policy type
    * @return boolean true if yes, else false
    */
    public boolean isPresent(int policyName) {
        if (IdAssignmentStrategy.USER_ID == policyName) {
            return true;
        } else {
            return false;
        }
    }

   /**
    * validate policy type
    * @param policy type
    * @throws org.omg.PortableServer.POAPackage.WrongPolicy
    */
    public void validate(int policy)
        throws org.omg.PortableServer.POAPackage.WrongPolicy {
        if (!isPresent(policy)) {
            throw new org.omg.PortableServer.POAPackage.WrongPolicy();
        }
    }

   /**
    * Check if the user id was generated by this strategy -- defaults to 
    * true
    * @param id  user id
    * @return boolean true always
    */
    public boolean verifyID(byte[] id) {
        return true;
    }

}
